name: Security Pipeline 

on:
  push:
    branches:
      - main 
  
  pull_request: 

jobs: 
  secret-scan:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0


      - name: Run Gitleaks 
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_COMMENTS: "false"
    
  
  sast: 
    runs-on: ubuntu-latest
    needs: secret-scan

    steps:
      - name:  Checkout Repository
        uses: actions/checkout@v4

      - name: Run Semgrep 
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/security-audit
    
  Trivy-filesystem: 
    runs-on: ubuntu-latest 
    needs: sast

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4 

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with: 
          scan-type: fs
          scan-ref: .
          scanners: vuln,misconfig 
          format: sarif
          output: reports/trivy-fs.sarif
          severity: HIGH,CRITICAL
          exit-code: "0"
          ignore-unfixed: true
      
      - name: Upload Trivy Filesystem Report 
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: reports/trivy-fs.sarif

  Trivy-image: 
    runs-on: ubuntu-latest
    needs: Trivy-filesystem 


    steps:
    - name: Checkout Repository 
      uses: actions/checkout@v4

    - name: Build Juice Shop Image 
      run: |
        docker pull bkimminich/juice-shop:latest
        docker tag bkimminich/juice-shop:latest secure-cicd-juice-shop:latest

    - name: Scan Docker Image 
      uses: aquasecurity/trivy-action@v0.36.0
      with:
        image-ref: secure-cicd-juice-shop:latest
        format: sarif
        output: reports/trivy-image.sarif
        severity: HIGH,CRITICAL
        exit-code: "0"
        ignore-unfixed: true

    - name: Upload Trivy Image Report 
      uses: actions/upload-artifact@v4
      with: 
        name: trivy-image-report 
        path: reports/trivy-image.sarif

  dast: 
    runs-on: ubuntu-latest 
    needs: Trivy-image


    steps: 
    - name: Start Juice Shop 
      run: docker run -d --name juice-shop -p 3000:3000 bkimminich/juice-shop:latest
    
    - name: Wait for Juice Shop
      run: |
        for i in {1..30}; do 
          if curl -fsS http://localhost:3000 > /dev/null; then 
            echo "Juice Shop ready"
            exit 0
          fi
          sleep 2
        done 

        echo "Juice Shop failed to start"
        docker logs juice-shop
        exit 1

    - name: Run ZAP Baseline Scan 
      uses: zaproxy/action-baseline@v0.15.0
      with:
        target: "http://localhost:3000"
        fail_action: false 
        allow_issue_writing: false 
        artifact_name: zap-report 

      
